### ISSUE TITLE
It could accept expired JWT tokens with the cache

### ISSUE THREAD

**Issue by dgrelaud** [Ideolys/fpark#5]
Why don't we use kitten-jwt which is battle-tested with such cases? 
Something was missing? 

https://github.com/Ideolys/fpark/blob/2075be99c0f9bd14fefa51550f6c3c7a42b364bf/src/commons/auth.js#L84

*Oui, on speak in english entre français à 2 mètres l'un de l'autre 😁*

**Comment by matthieurobin** [comment]
fixed in v0.6.6
